# ============================================
# coupon-service - 本地最小配置
# ============================================

spring:
  application:
    name: coupon-service
  config:
    import:
      - optional:nacos:application.yml
      - optional:nacos:application-seata.yml
      - optional:nacos:coupon-service.yml

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:nacos:8848}
      config:
        server-addr: ${NACOS_SERVER_ADDR:nacos:8848}
        file-extension: yml

seata:
  service:
    vgroup-mapping:
       mall_tx_group: default
